import { readFile, writeFile } from 'node:fs/promises';

const bundleUrl = new URL('../node_modules/commonmark/dist/commonmark.js', import.meta.url);
const outputUrl = new URL('../index.js', import.meta.url);
const bundle = await readFile(bundleUrl, 'utf8');
const firstNewline = bundle.indexOf('\n');
const bodyStart = bundle.indexOf('    function isContainer');
const bodyEnd = bundle.lastIndexOf('\n})));');

if (firstNewline < 0 || bodyStart < 0 || bodyEnd < bodyStart) {
  throw new Error('Unsupported commonmark browser bundle layout. Update scripts/build.js for the new version.');
}

const licenseHeader = bundle.slice(0, firstNewline);
const body = bundle.slice(bodyStart, bodyEnd)
  .replace(/^[\t ]+/gm, indent => indent.replaceAll('\t', '    '))
  .replace(/[\t ]+$/gm, '');
const wrapper = String.raw`
const parser = new commonmark.Parser();
const renderer = new commonmark.HtmlRenderer({ softbreak: '<br>' });
const SAFE_LINK = /^(?:https?:\/\/|mailto:)/i;
const SAFE_IMAGE = /^https?:\/\//i;

function isSafe(destination, pattern) {
    return typeof destination === 'string' && pattern.test(destination);
}

// Raw HTML is always displayed as text. CommonMark still recognizes the
// construct, but these handlers escape it instead of passing it through.
renderer.html_inline = function(node) {
    this.out(node.literal);
};
renderer.html_block = function(node) {
    this.cr();
    this.out(node.literal);
    this.cr();
};

// Restrict links to explicit web and email URLs. Relative, protocol-relative,
// data, file, JavaScript, and other application URLs render as label text.
renderer.link = function(node, entering) {
    if (!isSafe(node.destination, SAFE_LINK)) {
        return;
    }
    if (entering) {
        const attributes = this.attrs(node);
        attributes.push(['href', this.esc(node.destination)]);
        if (node.title) {
            attributes.push(['title', this.esc(node.title)]);
        }
        attributes.push(['rel', 'noopener noreferrer']);
        this.tag('a', attributes);
    } else {
        this.tag('/a');
    }
};

// Images use the same tag-suppression mechanism as CommonMark's renderer so
// emphasis inside alt text remains plain text. Unsafe image destinations
// render only their alt text and never create a request-capable element.
renderer.image = function(node, entering) {
    const safe = isSafe(node.destination, SAFE_IMAGE);
    if (entering) {
        if (safe && this.disableTags === 0) {
            this.lit('<img src="' + this.esc(node.destination) + '" alt="');
        }
        this.disableTags += 1;
        return;
    }
    this.disableTags -= 1;
    if (safe && this.disableTags === 0) {
        if (node.title) {
            this.lit('" title="' + this.esc(node.title));
        }
        this.lit('" />');
    }
};

const renderCodeBlock = renderer.code_block;

function isExecutableBlock(node) {
    return node.info?.trim().split(/\s+/, 1)[0] === 'e';
}

// Executable fences remain escaped code blocks, but carry an explicit marker
// that consumers can discover without reparsing HTML or trusting CSS classes.
renderer.code_block = function(node) {
    if (!isExecutableBlock(node)) {
        renderCodeBlock.call(this, node);
        return;
    }
    this.cr();
    this.tag('pre', [['data-executable', 'true']]);
    this.tag('code', [['class', 'language-e']]);
    this.out(node.literal);
    this.tag('/code');
    this.tag('/pre');
    this.cr();
};

function normalizeSource(source) {
    return String(source ?? '')
        .replaceAll('\u0000', '')
        .replace(/\r\n?/g, '\n');
}

export function extractExecutableCommands(source) {
    const markdown = normalizeSource(source);
    if (!markdown) {
        return [];
    }
    const commands = [];
    const walker = parser.parse(markdown).walker();
    let event;
    while ((event = walker.next())) {
        if (event.entering && event.node.type === 'code_block' && isExecutableBlock(event.node)) {
            commands.push(event.node.literal);
        }
    }
    return commands;
}


/**
 * Render CommonMark to an HTML fragment.
 *
 * Raw HTML is escaped. Links are limited to http, https, and mailto; images
 * are limited to http and https. Soft line breaks intentionally become <br>
 * to preserve markdown-helper v1's note-taking behavior.
 */
export function renderMarkdown(source) {
    const markdown = normalizeSource(source);
    if (!markdown) {
        return '';
    }
    const html = renderer.render(parser.parse(markdown));
    return html.endsWith('\n') ? html.slice(0, -1) : html;
}
`;

const generated = `${licenseHeader}\n// Generated by npm run build. Do not edit this file directly.\nconst commonmark = {};\n(function (exports) { 'use strict';\n\n${body}\n})(commonmark);\n${wrapper}`;
await writeFile(outputUrl, generated);
